# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Tesla Ble Http Proxy [Full access]"
description: "Control Tesla vehicles over BLE with Home assistant [Full access version]"
version: "0.0.3-fa"
slug: "tbhp-full-access"
init: false
url: https://github.com/wimaha/TeslaBleHttpProxy
host_network: true
host_dbus: true
privileged: [NET_ADMIN]
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 0
schema:
  cache_max_age: int?
  proxy_port: port?
  scan_timeout: int?
  log_level: list(DEBUG|INFO|WARN|ERROR|FATAL)?

full_access: false
