# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "BLE Test"
description: "Test BLE devices"
version: "0.0.1"
slug: "tblet"
init: false
url: https://github.com/Lenart12/vehicle-command/blob/main/cmd/test-ble/main.go
host_network: true
host_dbus: true
privileged: [NET_ADMIN]
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  bd_addr: "00:00:00:00:00:00"
schema:
  bd_addr: match(^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$)?
full_access: true
