# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Tesla Ble Http Proxy"
description: "Control Tesla vehicles over BLE with Home assistant"
version: "0.2.1"
slug: "tbhp"
init: false
apparmor: true
url: https://github.com/wimaha/TeslaBleHttpProxy
host_dbus: true
host_network: true
privileged: [NET_ADMIN]
panel_icon: mdi:car-wireless
discovery:
  - tbhp # TeslaBleHttpProxy
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 0
schema:
  bt_adapter: match(^hci\d+$)?
  raw_hci: bool?
  proxy_port: port?
  cache_max_age: int?
  scan_timeout: int?
  log_level: list(DEBUG|INFO|WARN|ERROR|FATAL)?
